const home = {
  GET_CONTENT: 'GET_CONTENT',
  STORE_CONTENT: 'STORE_CONTENT',
  INCREMENT: 'INCREMENT',
  ERROR_FETCHING_CONTENT: 'ERROR_FETCHING_CONTENT',
};

export default home;


export const GET_CONTENT = 'GET_CONTENT';
export type GET_CONTENT = typeof GET_CONTENT;

export const STORE_CONTENT = 'STORE_CONTENT';
export type STORE_CONTENT = typeof STORE_CONTENT;

export const INCREMENT = 'INCREMENT';
export type INCREMENT = typeof INCREMENT;

export const ERROR_FETCHING_CONTENT = 'ERROR_FETCHING_CONTENT';
export type ERROR_FETCHING_CONTENT = typeof ERROR_FETCHING_CONTENT;
